### ISSUE TITLE
Expression data

### ISSUE THREAD

**Issue by nitishkumarmishra** [shivaprasad-patil/LIMMA-Python-implementation#1]
Hi Shiva,
I didn't find an expression file for the limma example. Can you please provide the expression data link?

Thanks
Nitish

**Comment by shivaprasad-patil** [comment]
Hi Nitish,

You can download a dataset from TCGA using this link ([https://www.cbioportal.org/datasets]), the files will be in .txt format just convert it to .xlsx format using Excel.
Make sure you download corresponding clinical data to build a design matrix for comparison.

Hope this helps.
